### ISSUE TITLE
check out my version

### ISSUE THREAD

**Issue by Xample33** [DuroDaCoder/Rainbowium#12]
Hi man, github don't allow to direct message user so i'm writing here.
i created a new version of the bot (without setup and auto open r6s), if you want to check my job you're welcome :)
thx.

**Comment by DuroDaCoder** [comment]
Hi, thanks for messaging me. You can always contact me trough my discord server.

Your program looks nice, setup.bat is needed in my opinion. Some people don't know how to install python or modules so I made that script to make my life easier.

Thanks - Bob
